### ISSUE TITLE
Docker ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by JanisPlayer** [ParisNeo/Gpt4All-webui#24]
So the Docker version seems to have problems, requests don't seem to be found.
Edit: Same error even without Docker.
Edit with https://codeload.github.com/ParisNeo/gpt4all-ui/zip/refs/tags/v0.0.9 same.
Edit: I use this Version: https://github.com/ParisNeo/gpt4all-ui

```
root@server:/home/gpt4all/Gpt4All-webui# docker-compose -f docker-compose.yml down --rmi all
Removing gpt4all-webui_webui_1 ... done
Removing network gpt4all-webui_default
Removing image gpt4all-webui_webui

root@server:/home/gpt4all/Gpt4All-webui# docker-compose -f docker-compose.yml build --no-cache
Building webui
Sending build context to Docker daemon   30.4MB
Step 1/11 : FROM python:3.10
 ---> df5a406e137e
Step 2/11 : WORKDIR /srv
 ---> Running in 987f7c2f8388
Removing intermediate container 987f7c2f8388
 ---> 4fa0d39dc275
Step 3/11 : COPY ./requirements.txt .
 ---> 3b67637f1612
Step 4/11 : RUN python3 -m venv venv && . venv/bin/activate
 ---> Running in 2ab947c90f97
Removing intermediate container 2ab947c90f97
 ---> a69de40014a4
Step 5/11 : RUN python3 -m pip install --no-cache-dir -r requirements.txt --upgrade pip
 ---> Running in a41979488974
Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (23.0.1)
Collecting pip
  Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 3.2 MB/s eta 0:00:00
Collecting tqdm
  Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 1.5 MB/s eta 0:00:00
Collecting flask
  Downloading Flask-2.3.2-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.9/96.9 kB 1.3 MB/s eta 0:00:00
Collecting flask_socketio
  Downloading Flask_SocketIO-5.3.4-py3-none-any.whl (17 kB)
Collecting pytest
  Downloading pytest-7.3.1-py3-none-any.whl (320 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.5/320.5 kB 1.4 MB/s eta 0:00:00
Collecting pyyaml
  Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 kB 1.6 MB/s eta 0:00:00
Collecting markdown
  Downloading Markdown-3.4.3-py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.9/93.9 kB 2.0 MB/s eta 0:00:00
Collecting gevent
  Downloading gevent-22.10.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 1.6 MB/s eta 0:00:00
Collecting gevent-websocket
  Downloading gevent_websocket-0.10.1-py3-none-any.whl (22 kB)
Collecting pyaipersonality>=0.0.14
  Downloading pyaipersonality-1.0.1-py3-none-any.whl (26 kB)
Collecting Jinja2>=3.1.2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 1.6 MB/s eta 0:00:00
Collecting itsdangerous>=2.1.2
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting blinker>=1.6.2
  Downloading blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting click>=8.1.3
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 1.5 MB/s eta 0:00:00
Collecting Werkzeug>=2.3.3
  Downloading Werkzeug-2.3.4-py3-none-any.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.5/242.5 kB 1.7 MB/s eta 0:00:00
Collecting python-socketio>=5.0.2
  Downloading python_socketio-5.8.0-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 2.0 MB/s eta 0:00:00
Collecting exceptiongroup>=1.0.0rc8
  Downloading exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Collecting iniconfig
  Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting packaging
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 2.4 MB/s eta 0:00:00
Collecting tomli>=1.0.0
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting pluggy<2.0,>=0.12
  Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting zope.interface
  Downloading zope.interface-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (246 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.0/247.0 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (from gevent->-r requirements.txt (line 7)) (65.5.1)
Collecting greenlet>=2.0.0
  Downloading greenlet-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (613 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.7/613.7 kB 1.9 MB/s eta 0:00:00
Collecting zope.event
  Downloading zope.event-4.6-py2.py3-none-any.whl (6.8 kB)
Collecting Pillow
  Downloading Pillow-9.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 2.3 MB/s eta 0:00:00
Collecting flask-cors
  Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting simple-websocket
  Downloading simple_websocket-0.10.1-py3-none-any.whl (7.5 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting bidict>=0.21.0
  Downloading bidict-0.22.1-py3-none-any.whl (35 kB)
Collecting python-engineio>=4.3.0
  Downloading python_engineio-4.4.1-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.4/53.4 kB 1.9 MB/s eta 0:00:00
Collecting Six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting wsproto
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting h11<1,>=0.9.0
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 1.9 MB/s eta 0:00:00
Installing collected packages: zope.interface, zope.event, tqdm, tomli, Six, pyyaml, python-engineio, pluggy, pip, Pillow, packaging, MarkupSafe, markdown, itsdangerous, iniconfig, h11, greenlet, exceptiongroup, click, blinker, bidict, wsproto, Werkzeug, python-socketio, pytest, Jinja2, gevent, simple-websocket, gevent-websocket, flask, flask_socketio, flask-cors, pyaipersonality
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.3 Pillow-9.5.0 Six-1.16.0 Werkzeug-2.3.4 bidict-0.22.1 blinker-1.6.2 click-8.1.3 exceptiongroup-1.1.1 flask-2.3.2 flask-cors-3.0.10 flask_socketio-5.3.4 gevent-22.10.2 gevent-websocket-0.10.1 greenlet-2.0.2 h11-0.14.0 iniconfig-2.0.0 itsdangerous-2.1.2 markdown-3.4.3 packaging-23.1 pip-23.1.2 pluggy-1.0.0 pyaipersonality-1.0.1 pytest-7.3.1 python-engineio-4.4.1 python-socketio-5.8.0 pyyaml-6.0 simple-websocket-0.10.1 tomli-2.0.1 tqdm-4.65.0 wsproto-1.2.0 zope.event-4.6 zope.interface-6.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container a41979488974
 ---> 207a0f62bcec
Step 6/11 : COPY ./app.py /srv/app.py
 ---> c693d7042ac8
Step 7/11 : COPY ./gpt4all_api /srv/gpt4all_api
 ---> d2269e73e4db
Step 8/11 : COPY ./backends /srv/backends
 ---> bff1c37df6c5
Step 9/11 : COPY ./static /srv/static
 ---> d6dded520f3b
Step 10/11 : COPY ./templates /srv/templates
 ---> 322f8f31ff5a
Step 11/11 : CMD ["python", "app.py", "--host", "0.0.0.0", "--port", "9600", "--db_path", "data/database.db"]
 ---> Running in 8b73df2deb2e
Removing intermediate container 8b73df2deb2e
 ---> 6cf0bb22b532
Successfully built 6cf0bb22b532
Successfully tagged gpt4all-webui_webui:latest

root@server:/home/gpt4all/Gpt4All-webui# docker-compose -f docker-compose.yml up
Creating network "gpt4all-webui_default" with the default driver
Creating gpt4all-webui_webui_1 ... done
Attaching to gpt4all-webui_webui_1
webui_1  | Traceback (most recent call last):
webui_1  |   File "/srv/app.py", line 44, in <module>
webui_1  |     import requests
webui_1  | ModuleNotFoundError: No module named 'requests'
gpt4all-webui_webui_1 exited with code 1
```

```
./webui.sh
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHH     .HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHH.     ,HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHH.##  HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHH#.HHHHH_*,*,*,*,*,*,*,*,***,*,**#HHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHH.*,,***,***,***,***,***,***,*******HHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHH*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*,,,,,HHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH.,,,***,***,***,***,***,***,***,***,***,***_HHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH*,,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*HHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHH#,***,***,***,***,***,***,***,***,***,***,***,**HHHHHHHHHHHHHHHHH
HHHHHHHHHH..HHH,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*#HHHHHHHHHHHHHHHH
HHHHHHH,,,**,_H*,***,***,***,,,*,***,***,***,**,,,**,***,***,***H,,*,***HHHHHHHH
HHHHHH.*,,,*,,,,,*,*,*,***#HHHHH.,,*,*,*,*,**_HHHHH.,*,*,*,*,*,*,*,*****HHHHHHHH
HHHHHH.*,***,*,*,***,***,.HHHHHHH_**,***,****HHHHHHH.***,***,***,*******HHHHHHHH
HHHHHH.,,,,,,,,,,,,,,,,,,,.HHHHH.,,,,,,,,,,,,.HHHHHH,,,,,,,,,,,,,,,,,***HHHHHHHH
HHHHHH.,,,,,,_H,,,**,***,***,,,*,***,***,***,**,,,,*,***,***,***H***,***HHHHHHHH
HHHHHHH.,,,,*.H,,,,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,***H*,,,,_HHHHHHHHH
HHHHHHHHHHHHHHH*,***,***,**,,***,***,***,***,***,***,***,***,**.HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH,,,,,,,,*,,#H#,,,,,*,,,*,,,,,,,,*#H*,,,,,,,,,**HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH,,*,***,***,**_.HHHHHHHHHHHHH#*,,,*,***,***,*HHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHH,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*HHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHH**,***,***,***,***,***,***,***,***,***,***,*.HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHH*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHH**,***,***,*******_..HHHHHHHHH.#_*,*,,,***,***HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH*,*,*,******#HHHHHHHHHHHHHHHHHHHHHHHHHHHH._**,,,.HHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH.,,*,***.HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.*#HHHHHHHHHHHH
HHHHHHHHHHHHHHH_,,,*.HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHH,,#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHH.HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
Internet Connection working fine
Checking for Git...is installed
Pulling latest changes
From https://github.com/ParisNeo/Gpt4All-webui
 * branch            main       -> FETCH_HEAD
Already up to date.
Pulling latest version...
Already up to date.
Checking for python3.10...is installed
Checking for venv module...venv module is not available. Would you like to install it? [Y/N] Y
Installing venv module...
OK:1 http://de.archive.ubuntu.com/ubuntu jammy InRelease
Holen:2 http://de.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Holen:3 http://de.archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]
Holen:4 http://de.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
OK:5 https://packagecloud.io/ookla/speedtest-cli/ubuntu jammy InRelease
Es wurden 337 kB in 2 s geholt (189 kB/s).
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Aktualisierung für 18 Pakete verfügbar. Führen Sie »apt list --upgradable« aus, um sie anzuzeigen.
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  python3-pip-whl python3-setuptools-whl
Die folgenden NEUEN Pakete werden installiert:
  python3-pip-whl python3-setuptools-whl python3.10-venv
0 aktualisiert, 3 neu installiert, 0 zu entfernen und 18 nicht aktualisiert.
Es müssen 2.473 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 2.882 kB Plattenplatz zusätzlich benutzt.
Holen:1 http://de.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 python3-pip-whl all 22.0.2+dfsg-1ubuntu0.2 [1.679 kB]
Holen:2 http://de.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 python3-setuptools-whl all 59.6.0-1.2ubuntu0.22.04.1 [788 kB]
Holen:3 http://de.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 python3.10-venv amd64 3.10.6-1~22.04.2ubuntu1 [5.718 B]
Es wurden 2.473 kB in 1 s geholt (4.018 kB/s).
Vormals nicht ausgewähltes Paket python3-pip-whl wird gewählt.
(Lese Datenbank ... 165034 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../python3-pip-whl_22.0.2+dfsg-1ubuntu0.2_all.deb ...
Entpacken von python3-pip-whl (22.0.2+dfsg-1ubuntu0.2) ...
Vormals nicht ausgewähltes Paket python3-setuptools-whl wird gewählt.
Vorbereitung zum Entpacken von .../python3-setuptools-whl_59.6.0-1.2ubuntu0.22.04.1_all.deb ...
Entpacken von python3-setuptools-whl (59.6.0-1.2ubuntu0.22.04.1) ...
Vormals nicht ausgewähltes Paket python3.10-venv wird gewählt.
Vorbereitung zum Entpacken von .../python3.10-venv_3.10.6-1~22.04.2ubuntu1_amd64.deb ...
Entpacken von python3.10-venv (3.10.6-1~22.04.2ubuntu1) ...
python3-setuptools-whl (59.6.0-1.2ubuntu0.22.04.1) wird eingerichtet ...
python3-pip-whl (22.0.2+dfsg-1ubuntu0.2) wird eingerichtet ...
python3.10-venv (3.10.6-1~22.04.2ubuntu1) wird eingerichtet ...
Scanning processes...
Scanning processor microcode...
Scanning linux images...

Running kernel seems to be up-to-date.

The processor microcode seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
Creating virtual environment...is created
Activating virtual environment...is active
Installing requirements...
Requirement already satisfied: pip in ./env/lib/python3.10/site-packages (22.0.2)
Collecting pip
  Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 8.5 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-23.1.2
Collecting tqdm (from -r requirements.txt (line 1))
  Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 1.5 MB/s eta 0:00:00
Collecting flask (from -r requirements.txt (line 2))
  Downloading Flask-2.3.2-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.9/96.9 kB 6.5 MB/s eta 0:00:00
Collecting flask_socketio (from -r requirements.txt (line 3))
  Downloading Flask_SocketIO-5.3.4-py3-none-any.whl (17 kB)
Collecting pytest (from -r requirements.txt (line 4))
  Downloading pytest-7.3.1-py3-none-any.whl (320 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.5/320.5 kB 404.2 kB/s eta 0:00:00
Collecting pyyaml (from -r requirements.txt (line 5))
  Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 kB 1.2 MB/s eta 0:00:00
Collecting markdown (from -r requirements.txt (line 6))
  Downloading Markdown-3.4.3-py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.9/93.9 kB 1.3 MB/s eta 0:00:00
Collecting gevent (from -r requirements.txt (line 7))
  Downloading gevent-22.10.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 1.8 MB/s eta 0:00:00
Collecting gevent-websocket (from -r requirements.txt (line 8))
  Downloading gevent_websocket-0.10.1-py3-none-any.whl (22 kB)
Collecting pyaipersonality>=0.0.14 (from -r requirements.txt (line 9))
  Downloading pyaipersonality-1.0.1-py3-none-any.whl (26 kB)
Collecting Werkzeug>=2.3.3 (from flask->-r requirements.txt (line 2))
  Downloading Werkzeug-2.3.4-py3-none-any.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.5/242.5 kB 1.2 MB/s eta 0:00:00
Collecting Jinja2>=3.1.2 (from flask->-r requirements.txt (line 2))
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 1.5 MB/s eta 0:00:00
Collecting itsdangerous>=2.1.2 (from flask->-r requirements.txt (line 2))
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting click>=8.1.3 (from flask->-r requirements.txt (line 2))
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting blinker>=1.6.2 (from flask->-r requirements.txt (line 2))
  Downloading blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting python-socketio>=5.0.2 (from flask_socketio->-r requirements.txt (line 3))
  Downloading python_socketio-5.8.0-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 1.4 MB/s eta 0:00:00
Collecting iniconfig (from pytest->-r requirements.txt (line 4))
  Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting packaging (from pytest->-r requirements.txt (line 4))
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 2.3 MB/s eta 0:00:00
Collecting pluggy<2.0,>=0.12 (from pytest->-r requirements.txt (line 4))
  Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting exceptiongroup>=1.0.0rc8 (from pytest->-r requirements.txt (line 4))
  Downloading exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Collecting tomli>=1.0.0 (from pytest->-r requirements.txt (line 4))
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting zope.event (from gevent->-r requirements.txt (line 7))
  Downloading zope.event-4.6-py2.py3-none-any.whl (6.8 kB)
Collecting zope.interface (from gevent->-r requirements.txt (line 7))
  Downloading zope.interface-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (246 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.0/247.0 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./env/lib/python3.10/site-packages (from gevent->-r requirements.txt (line 7)) (59.6.0)
Collecting greenlet>=2.0.0 (from gevent->-r requirements.txt (line 7))
  Downloading greenlet-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (613 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.7/613.7 kB 599.6 kB/s eta 0:00:00
Collecting Pillow (from pyaipersonality>=0.0.14->-r requirements.txt (line 9))
  Downloading Pillow-9.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 1.9 MB/s eta 0:00:00
Collecting flask-cors (from pyaipersonality>=0.0.14->-r requirements.txt (line 9))
  Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting simple-websocket (from pyaipersonality>=0.0.14->-r requirements.txt (line 9))
  Downloading simple_websocket-0.10.1-py3-none-any.whl (7.5 kB)
Collecting MarkupSafe>=2.0 (from Jinja2>=3.1.2->flask->-r requirements.txt (line 2))
  Downloading MarkupSafe-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting bidict>=0.21.0 (from python-socketio>=5.0.2->flask_socketio->-r requirements.txt (line 3))
  Downloading bidict-0.22.1-py3-none-any.whl (35 kB)
Collecting python-engineio>=4.3.0 (from python-socketio>=5.0.2->flask_socketio->-r requirements.txt (line 3))
  Downloading python_engineio-4.4.1-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.4/53.4 kB 991.5 kB/s eta 0:00:00
Collecting Six (from flask-cors->pyaipersonality>=0.0.14->-r requirements.txt (line 9))
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting wsproto (from simple-websocket->pyaipersonality>=0.0.14->-r requirements.txt (line 9))
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting h11<1,>=0.9.0 (from wsproto->simple-websocket->pyaipersonality>=0.0.14->-r requirements.txt (line 9))
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Installing collected packages: zope.interface, zope.event, tqdm, tomli, Six, pyyaml, python-engineio, pluggy, Pillow, packaging, MarkupSafe, markdown, itsdangerous, iniconfig, h11, greenlet, exceptiongroup, click, blinker, bidict, wsproto, Werkzeug, python-socketio, pytest, Jinja2, gevent, simple-websocket, gevent-websocket, flask, flask_socketio, flask-cors, pyaipersonality
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.3 Pillow-9.5.0 Six-1.16.0 Werkzeug-2.3.4 bidict-0.22.1 blinker-1.6.2 click-8.1.3 exceptiongroup-1.1.1 flask-2.3.2 flask-cors-3.0.10 flask_socketio-5.3.4 gevent-22.10.2 gevent-websocket-0.10.1 greenlet-2.0.2 h11-0.14.0 iniconfig-2.0.0 itsdangerous-2.1.2 markdown-3.4.3 packaging-23.1 pluggy-1.0.0 pyaipersonality-1.0.1 pytest-7.3.1 python-engineio-4.4.1 python-socketio-5.8.0 pyyaml-6.0 simple-websocket-0.10.1 tomli-2.0.1 tqdm-4.65.0 wsproto-1.2.0 zope.event-4.6 zope.interface-6.0
Traceback (most recent call last):
  File "/home/gpt4all/Gpt4All-webui/app.py", line 44, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by lucaasmth** [comment]
Hello, you can just add `requests` in requirements.txt and rebuild the image

**Comment by ParisNeo** [comment]
Done. Thanks for the info
