### ISSUE TITLE
TypeError: unsupported operand type(s) for

### ISSUE THREAD

**Issue by danterran00** [ParisNeo/Gpt4All-webui#27]
## Expected Behavior
Installation of webui

## Current Behavior
When executing the batch, the app is trying to start but getting issue

## Steps to Reproduce
Execute the installation webui.bat

The issue when installing:

HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHH     .HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHH.     ,HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHH.##  HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHH#.HHHHH/*,*,*,*,*,*,*,*,***,*,**#HHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHH.*,,***,***,***,***,***,***,*******HHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHH*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*,,,,,HHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH.,,,***,***,***,***,***,***,***,***,***,***/HHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH*,,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*HHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHH#,***,***,***,***,***,***,***,***,***,***,***,**HHHHHHHHHHHHHHHHH
HHHHHHHHHH..HHH,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*#HHHHHHHHHHHHHHHH
HHHHHHH,,,**,/H*,***,***,***,,,*,***,***,***,**,,,**,***,***,***H,,*,***HHHHHHHH
HHHHHH.*,,,*,,,,,*,*,*,***#HHHHH.,,*,*,*,*,**/HHHHH.,*,*,*,*,*,*,*,*****HHHHHHHH
HHHHHH.*,***,*,*,***,***,.HHHHHHH/**,***,****HHHHHHH.***,***,***,*******HHHHHHHH
HHHHHH.,,,,,,,,,,,,,,,,,,,.HHHHH.,,,,,,,,,,,,.HHHHHH,,,,,,,,,,,,,,,,,***HHHHHHHH
HHHHHH.,,,,,,/H,,,**,***,***,,,*,***,***,***,**,,,,*,***,***,***H***,***HHHHHHHH
HHHHHHH.,,,,*.H,,,,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,***H*,,,,/HHHHHHHHH
HHHHHHHHHHHHHHH*,***,***,**,,***,***,***,***,***,***,***,***,**.HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH,,,,,,,,*,,#H#,,,,,*,,,*,,,,,,,,*#H*,,,,,,,,,**HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH,,*,***,***,**/.HHHHHHHHHHHHH#*,,,*,***,***,*HHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHH,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*HHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHH**,***,***,***,***,***,***,***,***,***,***,*.HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHH*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*HHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHH**,***,***,*******/..HHHHHHHHH.#/*,*,,,***,***HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHH*,*,*,******#HHHHHHHHHHHHHHHHHHHHHHHHHHHH./**,,,.HHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH.,,*,***.HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.*#HHHHHHHHHHHH
HHHHHHHHHHHHHHH/,,,*.HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHH,,#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHH.HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
Checking internet connection
\e[32mInternet connection working fine
"Checking for git..."
"Git is installed."
checking git repository
GPT4All folder found
Pulling latest changes
Already up to date.
Checking for python..."Python is installed."
Checking for pip..."Pip is installed."
Updating pip setuptools and wheel
Requirement already satisfied: pip in c:\python310\lib\site-packages (23.1.2)
Requirement already satisfied: setuptools in c:\python310\lib\site-packages (67.8.0)
Requirement already satisfied: wheel in c:\python310\lib\site-packages (0.40.0)
Checking for virtual environment..."Virtual environment is installed."
Checking virtual environment.
Virtual environment already exists.
Activating virtual environment ...OK
Installing requirements ...
Requirement already satisfied: pip in c:\windows\system32\gpt4all\env\lib\site-packages (23.1.2)
Requirement already satisfied: tqdm in c:\windows\system32\gpt4all\env\lib\site-packages (from -r requirements.txt (line 1)) (4.65.0)
Requirement already satisfied: psutil in c:\windows\system32\gpt4all\env\lib\site-packages (from -r requirements.txt (line 2)) (5.9.5)
Requirement already satisfied: flask in c:\windows\system32\gpt4all\env\lib\site-packages (from -r requirements.txt (line 3)) (2.3.2)
Requirement already satisfied: flask_socketio in c:\windows\system32\gpt4all\env\lib\site-packages (from -r requirements.txt (line 4)) (5.3.4)
Requirement already satisfied: pytest in c:\windows\system32\gpt4all\env\lib\site-packages (from -r requirements.txt (line 5)) (7.3.1)
Requirement already satisfied: pyyaml in c:\windows\system32\gpt4all\env\lib\site-packages (from -r requirements.txt (line 6)) (6.0)
Requirement already satisfied: markdown in c:\windows\system32\gpt4all\env\lib\site-packages (from -r requirements.txt (line 7)) (3.4.3)
Requirement already satisfied: gevent in c:\windows\system32\gpt4all\env\lib\site-packages (from -r requirements.txt (line 8)) (22.10.2)
Requirement already satisfied: gevent-websocket in c:\windows\system32\gpt4all\env\lib\site-packages (from -r requirements.txt (line 9)) (0.10.1)
Requirement already satisfied: pyaipersonality>=0.0.14 in c:\windows\system32\gpt4all\env\lib\site-packages (from -r requirements.txt (line 10)) (1.0.1)
Requirement already satisfied: langchain in c:\windows\system32\gpt4all\env\lib\site-packages (from -r requirements.txt (line 11)) (0.0.191)
Requirement already satisfied: colorama in c:\windows\system32\gpt4all\env\lib\site-packages (from tqdm->-r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: Werkzeug>=2.3.3 in c:\windows\system32\gpt4all\env\lib\site-packages (from flask->-r requirements.txt (line 3)) (2.3.4)
Requirement already satisfied: Jinja2>=3.1.2 in c:\windows\system32\gpt4all\env\lib\site-packages (from flask->-r requirements.txt (line 3)) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\windows\system32\gpt4all\env\lib\site-packages (from flask->-r requirements.txt (line 3)) (2.1.2)
Requirement already satisfied: click>=8.1.3 in c:\windows\system32\gpt4all\env\lib\site-packages (from flask->-r requirements.txt (line 3)) (8.1.3)
Requirement already satisfied: blinker>=1.6.2 in c:\windows\system32\gpt4all\env\lib\site-packages (from flask->-r requirements.txt (line 3)) (1.6.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from flask->-r requirements.txt (line 3)) (6.6.0)
Requirement already satisfied: python-socketio>=5.0.2 in c:\windows\system32\gpt4all\env\lib\site-packages (from flask_socketio->-r requirements.txt (line 4)) (5.8.0)
Requirement already satisfied: iniconfig in c:\windows\system32\gpt4all\env\lib\site-packages (from pytest->-r requirements.txt (line 5)) (2.0.0)
Requirement already satisfied: packaging in c:\windows\system32\gpt4all\env\lib\site-packages (from pytest->-r requirements.txt (line 5)) (23.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in c:\windows\system32\gpt4all\env\lib\site-packages (from pytest->-r requirements.txt (line 5)) (1.0.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in c:\windows\system32\gpt4all\env\lib\site-packages (from pytest->-r requirements.txt (line 5)) (1.1.1)
Requirement already satisfied: tomli>=1.0.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from pytest->-r requirements.txt (line 5)) (2.0.1)
Requirement already satisfied: zope.event in c:\windows\system32\gpt4all\env\lib\site-packages (from gevent->-r requirements.txt (line 8)) (4.6)
Requirement already satisfied: zope.interface in c:\windows\system32\gpt4all\env\lib\site-packages (from gevent->-r requirements.txt (line 8)) (6.0)
Requirement already satisfied: setuptools in c:\windows\system32\gpt4all\env\lib\site-packages (from gevent->-r requirements.txt (line 8)) (56.0.0)
Requirement already satisfied: greenlet>=2.0.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from gevent->-r requirements.txt (line 8)) (2.0.2)
Requirement already satisfied: cffi>=1.12.2 in c:\windows\system32\gpt4all\env\lib\site-packages (from gevent->-r requirements.txt (line 8)) (1.15.1)
Requirement already satisfied: Pillow in c:\windows\system32\gpt4all\env\lib\site-packages (from pyaipersonality>=0.0.14->-r requirements.txt (line 10)) (9.5.0)
Requirement already satisfied: flask-cors in c:\windows\system32\gpt4all\env\lib\site-packages (from pyaipersonality>=0.0.14->-r requirements.txt (line 10)) (3.0.10)
Requirement already satisfied: simple-websocket in c:\windows\system32\gpt4all\env\lib\site-packages (from pyaipersonality>=0.0.14->-r requirements.txt (line 10)) (0.10.1)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in c:\windows\system32\gpt4all\env\lib\site-packages (from langchain->-r requirements.txt (line 11)) (2.0.15)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\windows\system32\gpt4all\env\lib\site-packages (from langchain->-r requirements.txt (line 11)) (3.8.4)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from langchain->-r requirements.txt (line 11)) (4.0.2)
Requirement already satisfied: dataclasses-json<0.6.0,>=0.5.7 in c:\windows\system32\gpt4all\env\lib\site-packages (from langchain->-r requirements.txt (line 11)) (0.5.7)
Requirement already satisfied: numexpr<3.0.0,>=2.8.4 in c:\windows\system32\gpt4all\env\lib\site-packages (from langchain->-r requirements.txt (line 11)) (2.8.4)
Requirement already satisfied: numpy<2,>=1 in c:\windows\system32\gpt4all\env\lib\site-packages (from langchain->-r requirements.txt (line 11)) (1.24.3)
Requirement already satisfied: openapi-schema-pydantic<2.0,>=1.2 in c:\windows\system32\gpt4all\env\lib\site-packages (from langchain->-r requirements.txt (line 11)) (1.2.4)
Requirement already satisfied: pydantic<2,>=1 in c:\windows\system32\gpt4all\env\lib\site-packages (from langchain->-r requirements.txt (line 11)) (1.10.8)
Requirement already satisfied: requests<3,>=2 in c:\windows\system32\gpt4all\env\lib\site-packages (from langchain->-r requirements.txt (line 11)) (2.31.0)
Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from langchain->-r requirements.txt (line 11)) (8.2.2)
Requirement already satisfied: attrs>=17.3.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 11)) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 11)) (3.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\windows\system32\gpt4all\env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 11)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 11)) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\windows\system32\gpt4all\env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 11)) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\windows\system32\gpt4all\env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain->-r requirements.txt (line 11)) (1.3.1)
Requirement already satisfied: pycparser in c:\windows\system32\gpt4all\env\lib\site-packages (from cffi>=1.12.2->gevent->-r requirements.txt (line 8)) (2.21)
Requirement already satisfied: marshmallow<4.0.0,>=3.3.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain->-r requirements.txt (line 11)) (3.19.0)
Requirement already satisfied: marshmallow-enum<2.0.0,>=1.5.1 in c:\windows\system32\gpt4all\env\lib\site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain->-r requirements.txt (line 11)) (1.5.1)
Requirement already satisfied: typing-inspect>=0.4.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain->-r requirements.txt (line 11)) (0.9.0)
Requirement already satisfied: zipp>=0.5 in c:\windows\system32\gpt4all\env\lib\site-packages (from importlib-metadata>=3.6.0->flask->-r requirements.txt (line 3)) (3.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from Jinja2>=3.1.2->flask->-r requirements.txt (line 3)) (2.1.3)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from pydantic<2,>=1->langchain->-r requirements.txt (line 11)) (4.6.3)
Requirement already satisfied: bidict>=0.21.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from python-socketio>=5.0.2->flask_socketio->-r requirements.txt (line 4)) (0.22.1)
Requirement already satisfied: python-engineio>=4.3.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from python-socketio>=5.0.2->flask_socketio->-r requirements.txt (line 4)) (4.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\windows\system32\gpt4all\env\lib\site-packages (from requests<3,>=2->langchain->-r requirements.txt (line 11)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\windows\system32\gpt4all\env\lib\site-packages (from requests<3,>=2->langchain->-r requirements.txt (line 11)) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\windows\system32\gpt4all\env\lib\site-packages (from requests<3,>=2->langchain->-r requirements.txt (line 11)) (2023.5.7)
Requirement already satisfied: Six in c:\windows\system32\gpt4all\env\lib\site-packages (from flask-cors->pyaipersonality>=0.0.14->-r requirements.txt (line 10)) (1.16.0)
Requirement already satisfied: wsproto in c:\windows\system32\gpt4all\env\lib\site-packages (from simple-websocket->pyaipersonality>=0.0.14->-r requirements.txt (line 10)) (1.2.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from typing-inspect>=0.4.0->dataclasses-json<0.6.0,>=0.5.7->langchain->-r requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\windows\system32\gpt4all\env\lib\site-packages (from wsproto->simple-websocket->pyaipersonality>=0.0.14->-r requirements.txt (line 10)) (0.14.0)
Checking models...
Virtual environment created and packages installed successfully.
Launching application...
Traceback (most recent call last):
  File "app.py", line 27, in <module>
    from pyaipersonality import AIPersonality
  File "C:\Windows\System32\GPT4All\env\lib\site-packages\pyaipersonality\__init__.py", line 159, in <module>
    class AIPersonality:
  File "C:\Windows\System32\GPT4All\env\lib\site-packages\pyaipersonality\__init__.py", line 168, in AIPersonality
    def __init__(self, personality_package_path: str|Path = None, model:LLMBinding=None, run_scripts=True):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by danterran00** [comment]
Hello,

It has success installed now, required Python v3.11.3. With older versions I got the previous error message
