### ISSUE TITLE
docker-compose steps fail due to missing personality file

### ISSUE THREAD

**Issue by sammcj** [ParisNeo/Gpt4All-webui#30]
## Expected Behaviour

The docker-compose to run successfully using the example instructions.

## Current Behaviour

After downloading the models to the volume, and following the readme for docker-compose as bellow the following error occurs:

```
docker compose -f docker-compose.yml build
docker compose -f docker-compose.yml up
```

```
gpt4all-webui-webui-1  |  ******************* Building Personality from main Process *************************
gpt4all-webui-webui-1  | Personality file not found or is corrupted (personalities/english/default/gpt4all).
gpt4all-webui-webui-1  | Please verify that the personality you have selected exists or select another personality. Some updates may lead to change in personality name or category, so check the personality selection in settings to be sure.
gpt4all-webui-webui-1  | Checking discussions database...
gpt4all-webui-webui-1  | Traceback (most recent call last):
gpt4all-webui-webui-1  |   File "/srv/gpt4all_api/api.py", line 188, in _rebuild_model
gpt4all-webui-webui-1  |     model_file = Path("models")/self.config["backend"]/self.config["model"]
gpt4all-webui-webui-1  | TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'
```

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

as above

## Possible Solution
If you have any suggestions on how to fix the issue, please describe them here.

## Context
Please provide any additional context about the issue.

## Screenshots
If applicable, add screenshots to help explain the issue.

**Comment by nutmilk10** [comment]
Added this line to the dockerfile

COPY ./web /srv/web

still seeing the same error, 
`gpt4all-webui-webui-1  | Checking discussions database...
gpt4all-webui-webui-1  | Traceback (most recent call last):
gpt4all-webui-webui-1  |   File "/srv/gpt4all_api/api.py", line 188, in _rebuild_model
gpt4all-webui-webui-1  |     model_file = Path("models")/self.config["backend"]/self.config["model"]
gpt4all-webui-webui-1  | TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'`

**Comment by sammcj** [comment]
Yeah that does fix a lot of other errors though.

I feel like this project needs a complete rewrite and test of the documentation around running in docker / docker-compose, most of it seems pretty broken.
