### ISSUE TITLE
Personality related error message hangs

### ISSUE THREAD

**Issue by sephdm** [ParisNeo/Gpt4All-webui#34]
## Expected Behavior
Please describChecking models...
Virtual environment created and packages installed successfully.
Launching application...
Traceback (most recent call last):
  File "app.py", line 27, in <module>
    from pyaipersonality import AIPersonality
  File "D:\Dokks\GitHub\Gpt4All-webui\Gpt4All-webui\env\lib\site-packages\pyaipersonality\__init__.py", line 159, in <module>
    class AIPersonality:
  File "D:\Dokks\GitHub\Gpt4All-webui\Gpt4All-webui\env\lib\site-packages\pyaipersonality\__init__.py", line 168, in AIPersonality
    def __init__(self, personality_package_path: str|Path = None, model:LLMBinding=None, run_scripts=True):
TypeError: unsupported operand type(s) for |: 'type' and 'type'e the behavior you are expecting.

I used the install personality batch file in the installations folder and I'm still getting this error.
## Current Behavior
Please describe the behavior you are currently experiencing.

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. Step 1
2. Step 2
3. Step 3

## Possible Solution
If you have any suggestions on how to fix the issue, please describe them here.

## Context
Please provide any additional context about the issue.

## Screenshots
If applicable, add screenshots to help explain the issue.

**Comment by ParisNeo** [comment]
Hi there. I didn't know there are people still using my good old GPT4All-webui

I suggest you move to the new LOLLMS-ui which is the offspring of that project that is today my main focus. It is way more advanced and much more capable with support of all that crawls on the internet about llms.

You can find it here: https://github.com/ParisNeo/lollms-webui

It has a much more advanced personality system with much more capabilities.
